### ISSUE TITLE
missing asset bmos for ibc bridging option from terra to injective on dapp

### ISSUE THREAD

**Issue by bitmos-io** [astroport-fi/astroport-token-lists#402]
not sure if i missed anything else, but we have updated the terra2 and injective token data, is there anything else to update for bridge to list the assets?

{
    "protocol": "Bitmos",
    "symbol": "BMOS",
    "token": "ibc/D9353C3B1407A7F7FE0A5CCB7D06249B57337888C95C6648AEAF2C83F4F3074E",
    "icon": "/img/bitmos.png",
    "decimals": 6,
    "originDenom": "cw20:terra1sxe8u2hjczlekwfkcq0rs28egt38pg3wqzfx4zcrese4fnvzzupsk9gjkq",
    "originChainId": "phoenix-1"
}

**Comment by afsardo** [comment]
Add PR please.
